version: "3"
services:
  chown:
    entrypoint: /etc/keystone/chown.sh
    network_mode: none
    volumes:
      - /etc/keystone/:/etc/keystone/:ro
      - data:/var/lib/keystone/
      - logs:/var/log/keystone/
    image: samyaple/loci-keystone:ubuntu-11.0.3
    user: root
    container_name: keystone-chown
  bootstrap:
    entrypoint: /etc/keystone/bootstrap.sh
    network_mode: host
    volumes:
      - /etc/keystone/:/etc/keystone/:ro
      - data:/var/lib/keystone/
      - logs:/var/log/keystone/
    environment:
      - KEYSTONE_BOOTSTRAP=${KEYSTONE_BOOTSTRAP}
      - LB_URI=https://keystone.yaple.net
      - OS_BOOTSTRAP_REGION_ID=RegionOne
      - OS_BOOTSTRAP_PASSWORD=${KEYSTONE_ADMIN_PASS:-$OS_BOOTSTRAP_PASSWORD}
    image: samyaple/loci-keystone:ubuntu-11.0.3
    user: keystone
    container_name: keystone-bootstrap
  keystone:
    entrypoint: /etc/keystone/keystone.sh
    network_mode: host
    volumes:
      - /etc/keystone/:/etc/keystone/:ro
      - data:/var/lib/keystone/
      - logs:/var/log/keystone/
    image: samyaple/loci-keystone:ubuntu-11.0.3
    user: keystone
    container_name: keystone
    restart: always
volumes:
  data:
  logs:
