version: "3"
services:
  chown:
    entrypoint: /etc/glance/chown.sh
    network_mode: none
    volumes:
      - /etc/glance/:/etc/glance/:ro
      - data:/var/lib/glance/
      - logs:/var/log/glance/
    image: samyaple/loci-glance:ubuntu-14.0.0-ceph
    user: root
    container_name: glance-chown
  bootstrap:
    entrypoint: /etc/glance/bootstrap.sh
    network_mode: host
    volumes:
      - /etc/glance/:/etc/glance/:ro
      - data:/var/lib/glance/
      - logs:/var/log/glance/
    environment:
      - GLANCE_BOOTSTRAP=${GLANCE_BOOTSTRAP}
    image: samyaple/loci-glance:ubuntu-14.0.0-ceph
    user: glance
    container_name: glance-bootstrap
  glance-api:
    entrypoint: /etc/glance/glance.sh
    command: glance-api
    network_mode: host
    volumes:
      - /etc/glance/:/etc/glance/:ro
      - /etc/ceph/:/etc/ceph/:ro
      - data:/var/lib/glance/
      - logs:/var/log/glance/
    image: samyaple/loci-glance:ubuntu-14.0.0-ceph
    user: glance
    container_name: glance-api
    restart: always
  glance-registry:
    entrypoint: /etc/glance/glance.sh
    command: glance-registry
    network_mode: host
    volumes:
      - /etc/glance/:/etc/glance/:ro
      - /etc/ceph/:/etc/ceph/:ro
      - data:/var/lib/glance/
      - logs:/var/log/glance/
    image: samyaple/loci-glance:ubuntu-14.0.0-ceph
    user: glance
    container_name: glance-registry
    restart: always
volumes:
  data:
  logs:
